#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	opt.load("compiler_cxx")

def configure(conf):
	conf.load("compiler_cxx")

	octave_ver = '3.8.0'
	octave_dir = "/usr/local/Cellar/octave/" + octave_ver

	conf.env.LIBPATH_MEX = [
		octave_dir+'/lib/octave/'+octave_ver, 
		octave_dir+'/lib/octave/'+octave_ver+'/oct/x86_64-apple-darwin13.1.0/'
	]

	conf.env.INCLUDES_MEX = [ octave_dir+'/include/octave-'+octave_ver+'/octave/' ]

	conf.check_cxx( use='MEX', cxxflags='-O2')

def build(bld):

	# targets = [
	# 	'constructor'
	# 	'destructor'
	# ]

	# for

	bld.objects(
		features='cxx cxxprogram',
		source='../src/network-fun.cpp ../src/network-obj.cpp constructor.cpp',
		target='constructor.mex',
		cxxflags=['-std=c++11','-O2','-Wall'],
		use=['MEX'],
		includes=[ 'mex','octave','coctinterp' ]
		);